dist: trusty
sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
env:
  - CXX=g++-6
# Build steps
script:
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev
  - ./travis-build.sh
